app:
  build: .
  ports:
   - "80:80"
  environment:
    CKAN_SITE_URL: http://catalog.dev
    DB_ENV_POSTGRESQL_USER: ckan
    DB_ENV_POSTGRESQL_PASS: pass
    DB_ENV_POSTGRESQL_DB: ckan
    DB_ENV_POSTGRESQL_PYCSW_DB: pycsw
  links:
   - redis
   - db
   - solr
redis:
  image: redis
db:
  build: docker/db
solr:
  build: docker/solr
